### ISSUE TITLE
How to test standalone plugin locally (with yarn link)

### ISSUE THREAD

**Issue by fidelcoria-aa** [K-Phoen/backstage-plugin-opsgenie#16]
>  ## Plugin Setup
> 
> 1. If you have standalone app (you didn't clone this repository), then do:
> 
> ```bash
> yarn add @k-phoen/backstage-plugin-opsgenie
> ```

What if I have a standalone app and I `did clone this repository` for local testing?

I cloned your repo. Executed `~/opsgenie> yarn && yarn tsc && yarn build-rollup && yarn link`
Then in my Custom app `~/my-backstage-app/packages/app> yarn link "@K-Phoen/backstage-plugin-opsgenie"`  then I manually add the dependency to packages/app/package.json and follow the instructions in the readme. finally `yarn start`

When I navigate to localhost:3000/opsgenie the app crashes with `invalid hook call` because there are multiple copies of react.

The docs suggest a fix: https://reactjs.org/warnings/invalid-hook-call-warning.html
> This problem can also come up when you use npm link or an equivalent. In that case, your bundler might “see” two Reacts — one in application folder and one in your library folder. Assuming myapp and mylib are sibling folders, one possible fix is to run npm link ../myapp/node_modules/react from mylib. This should make the library use the application’s React copy.

So I tried `~/opsgenie> npm link ../my-backstage-app/node_modules/react`

and app crashed with `useLocation() may be used only in the context of a <Router> component.` 

```
The above error occurred in the <Routes> component:
    in Routes (at Router.tsx:7)
    in Router (at App.tsx:148)
    in Route (at App.tsx:148)
    in Routes (at App.tsx:133)
    in div (created by SidebarPage)
    in SidebarPage (at Root.tsx:97)
    in Root (at App.tsx:132)
    in Route (created by AppRouter)
    in Routes (created by AppRouter)
    in SignInPageWrapper (created by AppRouter)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by AppRouter)
    in AppRouter (at App.tsx:130)
    in RoutingProvider (created by Provider)
    in CssBaseline (created by WithStyles(CssBaseline))
    in WithStyles(CssBaseline) (created by AppThemeProvider)
    in ThemeProvider (created by AppThemeProvider)
    in AppThemeProvider (created by Provider)
    in AppContextProvider (created by Provider)
    in ApiProvider (created by Provider)
    in Provider (at App.tsx:127)
    in App (at src/index.tsx:6)
```

I tracked this down to your src/Router.tsx
Please help 🙏

**Comment by Rugvip** [comment]
Documented here https://backstage.io/docs/getting-started/create-an-app#linking-in-local-backstage-packages !

You may also want to set up a local development environment of the plugin in `dev/`, which can be served with `yarn start` in the plugin. Refer to the plugins in the main repo for examples of how to set that up for now.

**Comment by fidelcoria-aa** [comment]
wow, this works! thanks, I should re-read the docs sometime.
