### ISSUE TITLE
Paginate OnCall page

### ISSUE THREAD

**Issue by kuangp** [K-Phoen/backstage-plugin-opsgenie#24]
The new On Call page is awesome! However, we have a lot of schedule items and am hitting `429 Too Many Requests` errors due to each card making separate requests hitting limits on the OpsGenie API. Is it possible to paginate this page to show X cards per page? and perhaps support some kind of Search or dropdown list of all schedule names to quickly find the on call card you're looking for?

**Comment by K-Phoen** [comment]
Definitely something I want to address, yes :)
