### ISSUE TITLE
Is there a documented DSL for component annotations?

### ISSUE THREAD

**Issue by voodooGQ** [K-Phoen/backstage-plugin-opsgenie#28]
https://github.com/K-Phoen/backstage-plugin-opsgenie#components-annotations

For the `component-selector` annotation an example is provided outlining how to target a specific `tag`. Are there other annotation values that can be used to target other things? What about targeting multiple services?

**Comment by K-Phoen** [comment]
Absolutely :)

This annotation accepts any valid [Opsgenie search query](https://support.atlassian.com/opsgenie/docs/search-queries-for-alerts/) for alerts.

I'll add a mention to this in the README, thanks for taking the time to open an issue.
