### ISSUE TITLE
Allow override of CardsPerPage on OnCallList component

### ISSUE THREAD

**Issue by Ma11hewThomas** [K-Phoen/backstage-plugin-opsgenie#76]
Hi,

Thanks for providing a great plugin, a small request from our operation teams has been to show more on-call team cards per pagination. We are displaying this page on a shared monitor. 12 works well for us and doesn't exceed API rate limits. 

A solution I have found is to allow the user to pass the desired count via config. 

I'm happy to contribute if there is an appetite for this. 

Thanks

**Comment by K-Phoen** [comment]
I opened a quick PR that should help :)

https://github.com/K-Phoen/backstage-plugin-opsgenie/pull/77
