### ISSUE TITLE
Add schedule's name to OnCallForScheduleCard

### ISSUE THREAD

**Issue by drankou** [K-Phoen/backstage-plugin-opsgenie#97]
It would be great to add a schedule's name next to the team owner on the `OnCallForScheduleCard` as one team could own multiple schedules and there are cards with the same name in this case which could be misleading.

It could be as simple as:
```
{schedule.ownerTeam.name} | {schedule.name}
```
[here](https://github.com/K-Phoen/backstage-plugin-opsgenie/blob/1e6afadced723172871d2c538abea230aac70510/src/components/OnCallList/OnCallList.tsx#L87)

Or you could add the "Team:" and "Schedule:" labels so it's more explicit.

**Comment by drankou** [comment]
Also noticed that the [search is done by schedule's **name**](https://github.com/K-Phoen/backstage-plugin-opsgenie/blob/1e6afadced723172871d2c538abea230aac70510/src/components/OnCallList/OnCallList.tsx#L122), not the Team(as[ the placeholder says](https://github.com/K-Phoen/backstage-plugin-opsgenie/blob/1e6afadced723172871d2c538abea230aac70510/src/components/OnCallList/OnCallList.tsx#L135))

**Comment by drankou** [comment]
@K-Phoen Could you please take a look? :)

**Comment by K-Phoen** [comment]
Hey!

You might be interested in https://github.com/K-Phoen/backstage-plugin-opsgenie/pull/98 :)

**Comment by drankou** [comment]
> Also noticed that the [search is done by schedule's **name**](https://github.com/K-Phoen/backstage-plugin-opsgenie/blob/1e6afadced723172871d2c538abea230aac70510/src/components/OnCallList/OnCallList.tsx#L122), not the Team(as[ the placeholder says](https://github.com/K-Phoen/backstage-plugin-opsgenie/blob/1e6afadced723172871d2c538abea230aac70510/src/components/OnCallList/OnCallList.tsx#L135))

@K-Phoen Doesn't seem that this one was fixed as a part of #98 🤔
